SELECT
        TO_CHAR(T.SALES_DATE, 'YYYY') AS YEAR
      , TO_CHAR(T.SALES_DATE, 'FMMM') AS MONTH
      , U.GENDER                      AS GENDER
      , COUNT(DISTINCT T.USER_ID)     AS USERS
FROM    ONLINE_SALE T
      , USER_INFO   U
WHERE   1=1
AND     T.USER_ID   = U.USER_ID
AND     U.GENDER    IS NOT NULL
GROUP BY
        TO_CHAR(T.SALES_DATE, 'YYYY')
      , TO_CHAR(T.SALES_DATE, 'FMMM')
      , U.GENDER
ORDER BY
        TO_NUMBER(TO_CHAR(T.SALES_DATE, 'YYYY'))
      , TO_NUMBER(TO_CHAR(T.SALES_DATE, 'FMMM'))
      , U.GENDER
;