SELECT
        BOOK_ID
      , TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') AS PUBLISHED_DATE
FROM    BOOK
WHERE   1=1
AND     CATEGORY        = '인문'
AND     PUBLISHED_DATE  >= TO_DATE('20210101', 'YYYYMMDD')
ORDER BY
        PUBLISHED_DATE
;